version: '2.1'

services:
  web:
#   Создаем контейнер с нашим приложением из докерфайла
    build:
      context: .
      dockerfile: ./Dockerfile
#   Перезагружать контейнер при ошибках
    restart: on-failure
#   Все пароли и ключи лучше хранить в .env-файле
    env_file:
      - prod.env
#   Порты для nginx
    expose:
      - 8000
    ports:
      - 8000:8000
#   Поднимать только после БД
    depends_on:
      - db
#   Советую делать волюм с кодом, тогда не придется 
#   перебилдивать контейнер каждый раз
    volumes:
      - .:/var/html/gistest
#   Запускаем сервер
    command: python manage.py runserver 0.0.0.0:8000


  db:
#   Используем официальные postgis-image
    image: pgrouting/pgrouting:13-3.1-3.2.0
    restart: on-failure
#   Насадил новую базу на старую дату
#   P.S. Всегда стоит делать волюм у базы, чтобы 
#     не потерять все данные при перебилдивании
#   Для кастомной папки с данными задаем в prod.env 
#     переменную PGDATA=/var/lib/postgres/data/pgdata
    volumes:
      - ./dbdata:/var/lib/postgres/data/pgdata
    env_file:
      - prod.env
    ports:
      - 5432:5432
    expose:
      - 5432
